/**
 * Packages the TextMate grammars from the `textmate-grammars-themes` submodule into
 * this crate so they can be embedded (behind Cargo features) via `include_str!`.
 *
 * It performs four steps:
 *   1. Copies every grammar JSON into `assets/grammars/`.
 *   2. Copies the upstream LICENSE / NOTICE for attribution.
 *   3. Generates `src/bundled_generated.rs` — a cfg-gated table of bundled grammars.
 *   4. Regenerates the `[features]` block of `Cargo.toml` (per-language, per-category,
 *      `top`, and `all` features — all off by default).
 *
 * Themes are intentionally NOT packaged; this crate is a tokenizer/parser only and
 * leaves colour themes to downstream libraries.
 *
 * Run with: `bun run package-grammars` (see package.json).
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, copyFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const tmGrammars = join(root, "textmate-grammars-themes/packages/tm-grammars")
const grammarsSrcDir = join(tmGrammars, "grammars")
const assetsDir = join(root, "assets/grammars")

if (!existsSync(grammarsSrcDir)) {
  console.error(
    `Submodule not found at ${grammarsSrcDir}.\n` +
      `Run 'bun run update-submodules' first.`,
  )
  process.exit(1)
}

// The metadata (scopeName, aliases, embedded langs, categories) lives in index.js.
const { grammars, injections } = await import(join(tmGrammars, "index.js"))

/** Grammars and injection grammars are both loadable definitions for us. */
type GrammarInfo = {
  name: string
  scopeName: string
  aliases?: string[]
  embedded?: string[]
  categories?: string[]
}
const all: GrammarInfo[] = [...grammars, ...injections]

// Curated "popular languages" set for the `top` feature. Filtered to names that
// actually exist so the list can't silently rot.
const TOP = [
  "javascript", "typescript", "jsx", "tsx", "json", "jsonc", "html", "css",
  "scss", "less", "python", "rust", "go", "java", "c", "cpp", "csharp", "ruby",
  "php", "shellscript", "yaml", "toml", "markdown", "sql", "vue", "lua",
  "kotlin", "swift", "xml",
]

const names = new Set(all.map((g) => g.name))
const featureName = (name: string) => `grammar-${name}`

// Reserved bare feature names must not collide with any `grammar-*` shape. (They
// can't, since those are prefixed — but guard against a category/bundle name clashing
// with a real grammar's bare usage just in case the upstream taxonomy changes.)
const categories = [...new Set(all.flatMap((g) => g.categories ?? []))].sort()
const reserved = new Set(["_bundled", "default", "top", "all", ...categories])
for (const g of all) {
  if (reserved.has(g.name)) {
    throw new Error(`Grammar name "${g.name}" collides with a reserved feature name`)
  }
}

// ---------------------------------------------------------------------------
// 1. Copy grammar JSON into assets/.
// ---------------------------------------------------------------------------
rmSync(assetsDir, { recursive: true, force: true })
mkdirSync(assetsDir, { recursive: true })

for (const g of all) {
  copyFileSync(join(grammarsSrcDir, `${g.name}.json`), join(assetsDir, `${g.name}.json`))
}
console.log(`Copied ${all.length} grammar JSON files to assets/grammars/`)

// ---------------------------------------------------------------------------
// 2. Copy upstream attribution.
// ---------------------------------------------------------------------------
for (const file of ["LICENSE", "NOTICE"]) {
  const src = join(tmGrammars, file)
  if (existsSync(src)) copyFileSync(src, join(root, "assets/grammars", `UPSTREAM-${file}`))
}

// ---------------------------------------------------------------------------
// 3. Generate src/bundled_generated.rs
// ---------------------------------------------------------------------------
const rustStr = (s: string) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
const rustSlice = (xs: string[]) => `&[${xs.map(rustStr).join(", ")}]`

const sorted = [...all].sort((a, b) => a.name.localeCompare(b.name))
const entries = sorted
  .map((g) => {
    const aliases = (g.aliases ?? []).filter((a) => a !== g.name)
    return [
      `    #[cfg(feature = ${rustStr(featureName(g.name))})]`,
      `    g.push(BundledGrammar {`,
      `        name: ${rustStr(g.name)},`,
      `        scope: ${rustStr(g.scopeName)},`,
      `        aliases: ${rustSlice(aliases)},`,
      `        json: include_str!("../assets/grammars/${g.name}.json"),`,
      `    });`,
    ].join("\n")
  })
  .join("\n")

const generatedRs = `//! @generated by scripts/package-grammars.ts — DO NOT EDIT.
//!
//! Each entry is gated behind its \`grammar-<name>\` Cargo feature, so only the
//! grammars a downstream crate opts into are compiled into the binary.

use crate::bundled::BundledGrammar;

/// Returns the bundled grammars enabled by the active Cargo features.
pub(crate) fn grammars() -> Vec<BundledGrammar> {
    #[allow(unused_mut)]
    let mut g = Vec::new();
${entries}
    g
}
`
writeFileSync(join(root, "src/bundled_generated.rs"), generatedRs)
console.log(`Generated src/bundled_generated.rs (${all.length} entries)`)

// ---------------------------------------------------------------------------
// 4. Regenerate the [features] block of Cargo.toml
// ---------------------------------------------------------------------------
const tomlLine = (k: string, deps: string[]) => `${k} = [${deps.map(rustStr).join(", ")}]`

const lines: string[] = []
lines.push("# Internal marker enabled by every grammar feature; gates the bundled module.")
lines.push(tomlLine("_bundled", []))
lines.push("")
lines.push("# One feature per grammar. Enabling it also enables its embedded grammars so")
lines.push("# that languages-in-languages (e.g. CSS in HTML) tokenize correctly.")
for (const g of sorted) {
  const deps = ["_bundled"]
  for (const e of g.embedded ?? []) {
    if (names.has(e)) deps.push(featureName(e))
  }
  lines.push(tomlLine(featureName(g.name), [...new Set(deps)]))
}
lines.push("")
lines.push("# Category bundles (from the upstream grammar taxonomy).")
for (const cat of categories) {
  const members = sorted.filter((g) => (g.categories ?? []).includes(cat)).map((g) => featureName(g.name))
  lines.push(tomlLine(cat, members))
}
lines.push("")
lines.push("# Curated set of popular languages.")
lines.push(tomlLine("top", TOP.filter((n) => names.has(n)).map(featureName)))
lines.push("")
lines.push("# Everything.")
lines.push(tomlLine("all", sorted.map((g) => featureName(g.name))))

const BEGIN = "# == BEGIN GENERATED FEATURES =="
const END = "# == END GENERATED FEATURES =="
const block = `${BEGIN}\n${lines.join("\n")}\n${END}`

const cargoPath = join(root, "Cargo.toml")
let cargo = readFileSync(cargoPath, "utf8")

if (cargo.includes(BEGIN) && cargo.includes(END)) {
  cargo = cargo.replace(
    new RegExp(`${BEGIN}[\\s\\S]*${END}`),
    block,
  )
} else if (/^\[features\]/m.test(cargo)) {
  // Insert the block right after the [features] header, preserving `default`.
  cargo = cargo.replace(/^\[features\][^\n]*\n/m, (m) => `${m}${block}\n`)
} else {
  cargo = `${cargo.trimEnd()}\n\n[features]\ndefault = []\n${block}\n`
}
writeFileSync(cargoPath, cargo)
console.log(
  `Updated Cargo.toml features: ${all.length} grammars, ${categories.length} categories, top, all`,
)
