//! @generated by scripts/package-grammars.ts — DO NOT EDIT.
//!
//! Each entry is gated behind its `grammar-<name>` Cargo feature, so only the
//! grammars a downstream crate opts into are compiled into the binary.

use crate::bundled::BundledGrammar;

/// Returns the bundled grammars enabled by the active Cargo features.
pub(crate) fn grammars() -> Vec<BundledGrammar> {
    #[allow(unused_mut)]
    let mut g = Vec::new();
    #[cfg(feature = "grammar-abap")]
    g.push(BundledGrammar {
        name: "abap",
        scope: "source.abap",
        aliases: &[],
        json: include_str!("../assets/grammars/abap.json"),
    });
    #[cfg(feature = "grammar-actionscript-3")]
    g.push(BundledGrammar {
        name: "actionscript-3",
        scope: "source.actionscript.3",
        aliases: &[],
        json: include_str!("../assets/grammars/actionscript-3.json"),
    });
    #[cfg(feature = "grammar-ada")]
    g.push(BundledGrammar {
        name: "ada",
        scope: "source.ada",
        aliases: &[],
        json: include_str!("../assets/grammars/ada.json"),
    });
    #[cfg(feature = "grammar-ahk")]
    g.push(BundledGrammar {
        name: "ahk",
        scope: "source.ahk",
        aliases: &["ahk1"],
        json: include_str!("../assets/grammars/ahk.json"),
    });
    #[cfg(feature = "grammar-ahk2")]
    g.push(BundledGrammar {
        name: "ahk2",
        scope: "source.ahk2",
        aliases: &[],
        json: include_str!("../assets/grammars/ahk2.json"),
    });
    #[cfg(feature = "grammar-angular-expression")]
    g.push(BundledGrammar {
        name: "angular-expression",
        scope: "expression.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-expression.json"),
    });
    #[cfg(feature = "grammar-angular-html")]
    g.push(BundledGrammar {
        name: "angular-html",
        scope: "text.html.derivative.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-html.json"),
    });
    #[cfg(feature = "grammar-angular-inline-style")]
    g.push(BundledGrammar {
        name: "angular-inline-style",
        scope: "inline-styles.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-inline-style.json"),
    });
    #[cfg(feature = "grammar-angular-inline-template")]
    g.push(BundledGrammar {
        name: "angular-inline-template",
        scope: "inline-template.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-inline-template.json"),
    });
    #[cfg(feature = "grammar-angular-let-declaration")]
    g.push(BundledGrammar {
        name: "angular-let-declaration",
        scope: "template.let.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-let-declaration.json"),
    });
    #[cfg(feature = "grammar-angular-template")]
    g.push(BundledGrammar {
        name: "angular-template",
        scope: "template.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-template.json"),
    });
    #[cfg(feature = "grammar-angular-template-blocks")]
    g.push(BundledGrammar {
        name: "angular-template-blocks",
        scope: "template.blocks.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-template-blocks.json"),
    });
    #[cfg(feature = "grammar-angular-ts")]
    g.push(BundledGrammar {
        name: "angular-ts",
        scope: "source.ts.ng",
        aliases: &[],
        json: include_str!("../assets/grammars/angular-ts.json"),
    });
    #[cfg(feature = "grammar-apache")]
    g.push(BundledGrammar {
        name: "apache",
        scope: "source.apacheconf",
        aliases: &[],
        json: include_str!("../assets/grammars/apache.json"),
    });
    #[cfg(feature = "grammar-apex")]
    g.push(BundledGrammar {
        name: "apex",
        scope: "source.apex",
        aliases: &[],
        json: include_str!("../assets/grammars/apex.json"),
    });
    #[cfg(feature = "grammar-apl")]
    g.push(BundledGrammar {
        name: "apl",
        scope: "source.apl",
        aliases: &[],
        json: include_str!("../assets/grammars/apl.json"),
    });
    #[cfg(feature = "grammar-applescript")]
    g.push(BundledGrammar {
        name: "applescript",
        scope: "source.applescript",
        aliases: &[],
        json: include_str!("../assets/grammars/applescript.json"),
    });
    #[cfg(feature = "grammar-ara")]
    g.push(BundledGrammar {
        name: "ara",
        scope: "source.ara",
        aliases: &[],
        json: include_str!("../assets/grammars/ara.json"),
    });
    #[cfg(feature = "grammar-asciidoc")]
    g.push(BundledGrammar {
        name: "asciidoc",
        scope: "text.asciidoc",
        aliases: &["adoc"],
        json: include_str!("../assets/grammars/asciidoc.json"),
    });
    #[cfg(feature = "grammar-asm")]
    g.push(BundledGrammar {
        name: "asm",
        scope: "source.asm.x86_64",
        aliases: &[],
        json: include_str!("../assets/grammars/asm.json"),
    });
    #[cfg(feature = "grammar-astro")]
    g.push(BundledGrammar {
        name: "astro",
        scope: "source.astro",
        aliases: &[],
        json: include_str!("../assets/grammars/astro.json"),
    });
    #[cfg(feature = "grammar-awk")]
    g.push(BundledGrammar {
        name: "awk",
        scope: "source.awk",
        aliases: &[],
        json: include_str!("../assets/grammars/awk.json"),
    });
    #[cfg(feature = "grammar-ballerina")]
    g.push(BundledGrammar {
        name: "ballerina",
        scope: "source.ballerina",
        aliases: &[],
        json: include_str!("../assets/grammars/ballerina.json"),
    });
    #[cfg(feature = "grammar-bat")]
    g.push(BundledGrammar {
        name: "bat",
        scope: "source.batchfile",
        aliases: &["batch"],
        json: include_str!("../assets/grammars/bat.json"),
    });
    #[cfg(feature = "grammar-beancount")]
    g.push(BundledGrammar {
        name: "beancount",
        scope: "text.beancount",
        aliases: &[],
        json: include_str!("../assets/grammars/beancount.json"),
    });
    #[cfg(feature = "grammar-berry")]
    g.push(BundledGrammar {
        name: "berry",
        scope: "source.berry",
        aliases: &["be"],
        json: include_str!("../assets/grammars/berry.json"),
    });
    #[cfg(feature = "grammar-bibtex")]
    g.push(BundledGrammar {
        name: "bibtex",
        scope: "text.bibtex",
        aliases: &[],
        json: include_str!("../assets/grammars/bibtex.json"),
    });
    #[cfg(feature = "grammar-bicep")]
    g.push(BundledGrammar {
        name: "bicep",
        scope: "source.bicep",
        aliases: &[],
        json: include_str!("../assets/grammars/bicep.json"),
    });
    #[cfg(feature = "grammar-bird2")]
    g.push(BundledGrammar {
        name: "bird2",
        scope: "source.bird2",
        aliases: &["bird"],
        json: include_str!("../assets/grammars/bird2.json"),
    });
    #[cfg(feature = "grammar-blade")]
    g.push(BundledGrammar {
        name: "blade",
        scope: "text.html.php.blade",
        aliases: &[],
        json: include_str!("../assets/grammars/blade.json"),
    });
    #[cfg(feature = "grammar-bsl")]
    g.push(BundledGrammar {
        name: "bsl",
        scope: "source.bsl",
        aliases: &["1c"],
        json: include_str!("../assets/grammars/bsl.json"),
    });
    #[cfg(feature = "grammar-c")]
    g.push(BundledGrammar {
        name: "c",
        scope: "source.c",
        aliases: &[],
        json: include_str!("../assets/grammars/c.json"),
    });
    #[cfg(feature = "grammar-c3")]
    g.push(BundledGrammar {
        name: "c3",
        scope: "source.c3",
        aliases: &[],
        json: include_str!("../assets/grammars/c3.json"),
    });
    #[cfg(feature = "grammar-cadence")]
    g.push(BundledGrammar {
        name: "cadence",
        scope: "source.cadence",
        aliases: &["cdc"],
        json: include_str!("../assets/grammars/cadence.json"),
    });
    #[cfg(feature = "grammar-cairo")]
    g.push(BundledGrammar {
        name: "cairo",
        scope: "source.cairo0",
        aliases: &[],
        json: include_str!("../assets/grammars/cairo.json"),
    });
    #[cfg(feature = "grammar-chapel")]
    g.push(BundledGrammar {
        name: "chapel",
        scope: "source.chapel",
        aliases: &["chpl"],
        json: include_str!("../assets/grammars/chapel.json"),
    });
    #[cfg(feature = "grammar-clarity")]
    g.push(BundledGrammar {
        name: "clarity",
        scope: "source.clar",
        aliases: &[],
        json: include_str!("../assets/grammars/clarity.json"),
    });
    #[cfg(feature = "grammar-clojure")]
    g.push(BundledGrammar {
        name: "clojure",
        scope: "source.clojure",
        aliases: &["clj"],
        json: include_str!("../assets/grammars/clojure.json"),
    });
    #[cfg(feature = "grammar-cmake")]
    g.push(BundledGrammar {
        name: "cmake",
        scope: "source.cmake",
        aliases: &[],
        json: include_str!("../assets/grammars/cmake.json"),
    });
    #[cfg(feature = "grammar-cobol")]
    g.push(BundledGrammar {
        name: "cobol",
        scope: "source.cobol",
        aliases: &[],
        json: include_str!("../assets/grammars/cobol.json"),
    });
    #[cfg(feature = "grammar-codeowners")]
    g.push(BundledGrammar {
        name: "codeowners",
        scope: "text.codeowners",
        aliases: &[],
        json: include_str!("../assets/grammars/codeowners.json"),
    });
    #[cfg(feature = "grammar-codeql")]
    g.push(BundledGrammar {
        name: "codeql",
        scope: "source.ql",
        aliases: &["ql"],
        json: include_str!("../assets/grammars/codeql.json"),
    });
    #[cfg(feature = "grammar-coffee")]
    g.push(BundledGrammar {
        name: "coffee",
        scope: "source.coffee",
        aliases: &["coffeescript"],
        json: include_str!("../assets/grammars/coffee.json"),
    });
    #[cfg(feature = "grammar-common-lisp")]
    g.push(BundledGrammar {
        name: "common-lisp",
        scope: "source.commonlisp",
        aliases: &["lisp"],
        json: include_str!("../assets/grammars/common-lisp.json"),
    });
    #[cfg(feature = "grammar-coq")]
    g.push(BundledGrammar {
        name: "coq",
        scope: "source.coq",
        aliases: &[],
        json: include_str!("../assets/grammars/coq.json"),
    });
    #[cfg(feature = "grammar-cpp")]
    g.push(BundledGrammar {
        name: "cpp",
        scope: "source.cpp",
        aliases: &["c++"],
        json: include_str!("../assets/grammars/cpp.json"),
    });
    #[cfg(feature = "grammar-cpp-macro")]
    g.push(BundledGrammar {
        name: "cpp-macro",
        scope: "source.cpp.embedded.macro",
        aliases: &[],
        json: include_str!("../assets/grammars/cpp-macro.json"),
    });
    #[cfg(feature = "grammar-crystal")]
    g.push(BundledGrammar {
        name: "crystal",
        scope: "source.crystal",
        aliases: &[],
        json: include_str!("../assets/grammars/crystal.json"),
    });
    #[cfg(feature = "grammar-csharp")]
    g.push(BundledGrammar {
        name: "csharp",
        scope: "source.cs",
        aliases: &["c#", "cs"],
        json: include_str!("../assets/grammars/csharp.json"),
    });
    #[cfg(feature = "grammar-css")]
    g.push(BundledGrammar {
        name: "css",
        scope: "source.css",
        aliases: &[],
        json: include_str!("../assets/grammars/css.json"),
    });
    #[cfg(feature = "grammar-csv")]
    g.push(BundledGrammar {
        name: "csv",
        scope: "text.csv",
        aliases: &[],
        json: include_str!("../assets/grammars/csv.json"),
    });
    #[cfg(feature = "grammar-cue")]
    g.push(BundledGrammar {
        name: "cue",
        scope: "source.cue",
        aliases: &[],
        json: include_str!("../assets/grammars/cue.json"),
    });
    #[cfg(feature = "grammar-cypher")]
    g.push(BundledGrammar {
        name: "cypher",
        scope: "source.cypher",
        aliases: &["cql"],
        json: include_str!("../assets/grammars/cypher.json"),
    });
    #[cfg(feature = "grammar-d")]
    g.push(BundledGrammar {
        name: "d",
        scope: "source.d",
        aliases: &[],
        json: include_str!("../assets/grammars/d.json"),
    });
    #[cfg(feature = "grammar-dart")]
    g.push(BundledGrammar {
        name: "dart",
        scope: "source.dart",
        aliases: &[],
        json: include_str!("../assets/grammars/dart.json"),
    });
    #[cfg(feature = "grammar-dax")]
    g.push(BundledGrammar {
        name: "dax",
        scope: "source.dax",
        aliases: &[],
        json: include_str!("../assets/grammars/dax.json"),
    });
    #[cfg(feature = "grammar-desktop")]
    g.push(BundledGrammar {
        name: "desktop",
        scope: "source.desktop",
        aliases: &[],
        json: include_str!("../assets/grammars/desktop.json"),
    });
    #[cfg(feature = "grammar-diff")]
    g.push(BundledGrammar {
        name: "diff",
        scope: "source.diff",
        aliases: &[],
        json: include_str!("../assets/grammars/diff.json"),
    });
    #[cfg(feature = "grammar-docker")]
    g.push(BundledGrammar {
        name: "docker",
        scope: "source.dockerfile",
        aliases: &["dockerfile"],
        json: include_str!("../assets/grammars/docker.json"),
    });
    #[cfg(feature = "grammar-dotenv")]
    g.push(BundledGrammar {
        name: "dotenv",
        scope: "source.dotenv",
        aliases: &[],
        json: include_str!("../assets/grammars/dotenv.json"),
    });
    #[cfg(feature = "grammar-dream-maker")]
    g.push(BundledGrammar {
        name: "dream-maker",
        scope: "source.dm",
        aliases: &[],
        json: include_str!("../assets/grammars/dream-maker.json"),
    });
    #[cfg(feature = "grammar-edge")]
    g.push(BundledGrammar {
        name: "edge",
        scope: "text.html.edge",
        aliases: &[],
        json: include_str!("../assets/grammars/edge.json"),
    });
    #[cfg(feature = "grammar-elixir")]
    g.push(BundledGrammar {
        name: "elixir",
        scope: "source.elixir",
        aliases: &[],
        json: include_str!("../assets/grammars/elixir.json"),
    });
    #[cfg(feature = "grammar-elm")]
    g.push(BundledGrammar {
        name: "elm",
        scope: "source.elm",
        aliases: &[],
        json: include_str!("../assets/grammars/elm.json"),
    });
    #[cfg(feature = "grammar-emacs-lisp")]
    g.push(BundledGrammar {
        name: "emacs-lisp",
        scope: "source.emacs.lisp",
        aliases: &["elisp"],
        json: include_str!("../assets/grammars/emacs-lisp.json"),
    });
    #[cfg(feature = "grammar-erb")]
    g.push(BundledGrammar {
        name: "erb",
        scope: "text.html.erb",
        aliases: &[],
        json: include_str!("../assets/grammars/erb.json"),
    });
    #[cfg(feature = "grammar-erlang")]
    g.push(BundledGrammar {
        name: "erlang",
        scope: "source.erlang",
        aliases: &["erl"],
        json: include_str!("../assets/grammars/erlang.json"),
    });
    #[cfg(feature = "grammar-es-tag-css")]
    g.push(BundledGrammar {
        name: "es-tag-css",
        scope: "inline.es6-css",
        aliases: &[],
        json: include_str!("../assets/grammars/es-tag-css.json"),
    });
    #[cfg(feature = "grammar-es-tag-glsl")]
    g.push(BundledGrammar {
        name: "es-tag-glsl",
        scope: "inline.es6-glsl",
        aliases: &[],
        json: include_str!("../assets/grammars/es-tag-glsl.json"),
    });
    #[cfg(feature = "grammar-es-tag-html")]
    g.push(BundledGrammar {
        name: "es-tag-html",
        scope: "inline.es6-html",
        aliases: &[],
        json: include_str!("../assets/grammars/es-tag-html.json"),
    });
    #[cfg(feature = "grammar-es-tag-sql")]
    g.push(BundledGrammar {
        name: "es-tag-sql",
        scope: "inline.tagged-template-sql",
        aliases: &[],
        json: include_str!("../assets/grammars/es-tag-sql.json"),
    });
    #[cfg(feature = "grammar-es-tag-xml")]
    g.push(BundledGrammar {
        name: "es-tag-xml",
        scope: "inline.es6-xml",
        aliases: &[],
        json: include_str!("../assets/grammars/es-tag-xml.json"),
    });
    #[cfg(feature = "grammar-fennel")]
    g.push(BundledGrammar {
        name: "fennel",
        scope: "source.fnl",
        aliases: &[],
        json: include_str!("../assets/grammars/fennel.json"),
    });
    #[cfg(feature = "grammar-fish")]
    g.push(BundledGrammar {
        name: "fish",
        scope: "source.fish",
        aliases: &[],
        json: include_str!("../assets/grammars/fish.json"),
    });
    #[cfg(feature = "grammar-fluent")]
    g.push(BundledGrammar {
        name: "fluent",
        scope: "source.ftl",
        aliases: &["ftl"],
        json: include_str!("../assets/grammars/fluent.json"),
    });
    #[cfg(feature = "grammar-fortran-fixed-form")]
    g.push(BundledGrammar {
        name: "fortran-fixed-form",
        scope: "source.fortran.fixed",
        aliases: &["f", "for", "f77"],
        json: include_str!("../assets/grammars/fortran-fixed-form.json"),
    });
    #[cfg(feature = "grammar-fortran-free-form")]
    g.push(BundledGrammar {
        name: "fortran-free-form",
        scope: "source.fortran.free",
        aliases: &["f90", "f95", "f03", "f08", "f18"],
        json: include_str!("../assets/grammars/fortran-free-form.json"),
    });
    #[cfg(feature = "grammar-fsharp")]
    g.push(BundledGrammar {
        name: "fsharp",
        scope: "source.fsharp",
        aliases: &["f#", "fs"],
        json: include_str!("../assets/grammars/fsharp.json"),
    });
    #[cfg(feature = "grammar-gdresource")]
    g.push(BundledGrammar {
        name: "gdresource",
        scope: "source.gdresource",
        aliases: &["tscn", "tres"],
        json: include_str!("../assets/grammars/gdresource.json"),
    });
    #[cfg(feature = "grammar-gdscript")]
    g.push(BundledGrammar {
        name: "gdscript",
        scope: "source.gdscript",
        aliases: &["gd"],
        json: include_str!("../assets/grammars/gdscript.json"),
    });
    #[cfg(feature = "grammar-gdshader")]
    g.push(BundledGrammar {
        name: "gdshader",
        scope: "source.gdshader",
        aliases: &[],
        json: include_str!("../assets/grammars/gdshader.json"),
    });
    #[cfg(feature = "grammar-genie")]
    g.push(BundledGrammar {
        name: "genie",
        scope: "source.genie",
        aliases: &[],
        json: include_str!("../assets/grammars/genie.json"),
    });
    #[cfg(feature = "grammar-gherkin")]
    g.push(BundledGrammar {
        name: "gherkin",
        scope: "text.gherkin.feature",
        aliases: &[],
        json: include_str!("../assets/grammars/gherkin.json"),
    });
    #[cfg(feature = "grammar-git-commit")]
    g.push(BundledGrammar {
        name: "git-commit",
        scope: "text.git-commit",
        aliases: &[],
        json: include_str!("../assets/grammars/git-commit.json"),
    });
    #[cfg(feature = "grammar-git-rebase")]
    g.push(BundledGrammar {
        name: "git-rebase",
        scope: "text.git-rebase",
        aliases: &[],
        json: include_str!("../assets/grammars/git-rebase.json"),
    });
    #[cfg(feature = "grammar-gleam")]
    g.push(BundledGrammar {
        name: "gleam",
        scope: "source.gleam",
        aliases: &[],
        json: include_str!("../assets/grammars/gleam.json"),
    });
    #[cfg(feature = "grammar-glimmer-js")]
    g.push(BundledGrammar {
        name: "glimmer-js",
        scope: "source.gjs",
        aliases: &["gjs"],
        json: include_str!("../assets/grammars/glimmer-js.json"),
    });
    #[cfg(feature = "grammar-glimmer-ts")]
    g.push(BundledGrammar {
        name: "glimmer-ts",
        scope: "source.gts",
        aliases: &["gts"],
        json: include_str!("../assets/grammars/glimmer-ts.json"),
    });
    #[cfg(feature = "grammar-glsl")]
    g.push(BundledGrammar {
        name: "glsl",
        scope: "source.glsl",
        aliases: &[],
        json: include_str!("../assets/grammars/glsl.json"),
    });
    #[cfg(feature = "grammar-gn")]
    g.push(BundledGrammar {
        name: "gn",
        scope: "source.gn",
        aliases: &[],
        json: include_str!("../assets/grammars/gn.json"),
    });
    #[cfg(feature = "grammar-gnuplot")]
    g.push(BundledGrammar {
        name: "gnuplot",
        scope: "source.gnuplot",
        aliases: &[],
        json: include_str!("../assets/grammars/gnuplot.json"),
    });
    #[cfg(feature = "grammar-go")]
    g.push(BundledGrammar {
        name: "go",
        scope: "source.go",
        aliases: &[],
        json: include_str!("../assets/grammars/go.json"),
    });
    #[cfg(feature = "grammar-graphql")]
    g.push(BundledGrammar {
        name: "graphql",
        scope: "source.graphql",
        aliases: &["gql"],
        json: include_str!("../assets/grammars/graphql.json"),
    });
    #[cfg(feature = "grammar-groovy")]
    g.push(BundledGrammar {
        name: "groovy",
        scope: "source.groovy",
        aliases: &[],
        json: include_str!("../assets/grammars/groovy.json"),
    });
    #[cfg(feature = "grammar-hack")]
    g.push(BundledGrammar {
        name: "hack",
        scope: "source.hack",
        aliases: &[],
        json: include_str!("../assets/grammars/hack.json"),
    });
    #[cfg(feature = "grammar-haml")]
    g.push(BundledGrammar {
        name: "haml",
        scope: "text.haml",
        aliases: &[],
        json: include_str!("../assets/grammars/haml.json"),
    });
    #[cfg(feature = "grammar-handlebars")]
    g.push(BundledGrammar {
        name: "handlebars",
        scope: "text.html.handlebars",
        aliases: &["hbs"],
        json: include_str!("../assets/grammars/handlebars.json"),
    });
    #[cfg(feature = "grammar-haskell")]
    g.push(BundledGrammar {
        name: "haskell",
        scope: "source.haskell",
        aliases: &["hs"],
        json: include_str!("../assets/grammars/haskell.json"),
    });
    #[cfg(feature = "grammar-haxe")]
    g.push(BundledGrammar {
        name: "haxe",
        scope: "source.hx",
        aliases: &[],
        json: include_str!("../assets/grammars/haxe.json"),
    });
    #[cfg(feature = "grammar-hcl")]
    g.push(BundledGrammar {
        name: "hcl",
        scope: "source.hcl",
        aliases: &[],
        json: include_str!("../assets/grammars/hcl.json"),
    });
    #[cfg(feature = "grammar-hjson")]
    g.push(BundledGrammar {
        name: "hjson",
        scope: "source.hjson",
        aliases: &[],
        json: include_str!("../assets/grammars/hjson.json"),
    });
    #[cfg(feature = "grammar-hlsl")]
    g.push(BundledGrammar {
        name: "hlsl",
        scope: "source.hlsl",
        aliases: &[],
        json: include_str!("../assets/grammars/hlsl.json"),
    });
    #[cfg(feature = "grammar-html")]
    g.push(BundledGrammar {
        name: "html",
        scope: "text.html.basic",
        aliases: &[],
        json: include_str!("../assets/grammars/html.json"),
    });
    #[cfg(feature = "grammar-html-derivative")]
    g.push(BundledGrammar {
        name: "html-derivative",
        scope: "text.html.derivative",
        aliases: &[],
        json: include_str!("../assets/grammars/html-derivative.json"),
    });
    #[cfg(feature = "grammar-http")]
    g.push(BundledGrammar {
        name: "http",
        scope: "source.http",
        aliases: &[],
        json: include_str!("../assets/grammars/http.json"),
    });
    #[cfg(feature = "grammar-hurl")]
    g.push(BundledGrammar {
        name: "hurl",
        scope: "source.hurl",
        aliases: &[],
        json: include_str!("../assets/grammars/hurl.json"),
    });
    #[cfg(feature = "grammar-hxml")]
    g.push(BundledGrammar {
        name: "hxml",
        scope: "source.hxml",
        aliases: &[],
        json: include_str!("../assets/grammars/hxml.json"),
    });
    #[cfg(feature = "grammar-hy")]
    g.push(BundledGrammar {
        name: "hy",
        scope: "source.hy",
        aliases: &[],
        json: include_str!("../assets/grammars/hy.json"),
    });
    #[cfg(feature = "grammar-imba")]
    g.push(BundledGrammar {
        name: "imba",
        scope: "source.imba",
        aliases: &[],
        json: include_str!("../assets/grammars/imba.json"),
    });
    #[cfg(feature = "grammar-ini")]
    g.push(BundledGrammar {
        name: "ini",
        scope: "source.ini",
        aliases: &["properties"],
        json: include_str!("../assets/grammars/ini.json"),
    });
    #[cfg(feature = "grammar-java")]
    g.push(BundledGrammar {
        name: "java",
        scope: "source.java",
        aliases: &[],
        json: include_str!("../assets/grammars/java.json"),
    });
    #[cfg(feature = "grammar-javascript")]
    g.push(BundledGrammar {
        name: "javascript",
        scope: "source.js",
        aliases: &["js", "cjs", "mjs"],
        json: include_str!("../assets/grammars/javascript.json"),
    });
    #[cfg(feature = "grammar-jinja")]
    g.push(BundledGrammar {
        name: "jinja",
        scope: "source.jinja",
        aliases: &[],
        json: include_str!("../assets/grammars/jinja.json"),
    });
    #[cfg(feature = "grammar-jinja-html")]
    g.push(BundledGrammar {
        name: "jinja-html",
        scope: "text.html.jinja",
        aliases: &[],
        json: include_str!("../assets/grammars/jinja-html.json"),
    });
    #[cfg(feature = "grammar-jison")]
    g.push(BundledGrammar {
        name: "jison",
        scope: "source.jison",
        aliases: &[],
        json: include_str!("../assets/grammars/jison.json"),
    });
    #[cfg(feature = "grammar-json")]
    g.push(BundledGrammar {
        name: "json",
        scope: "source.json",
        aliases: &[],
        json: include_str!("../assets/grammars/json.json"),
    });
    #[cfg(feature = "grammar-json5")]
    g.push(BundledGrammar {
        name: "json5",
        scope: "source.json5",
        aliases: &[],
        json: include_str!("../assets/grammars/json5.json"),
    });
    #[cfg(feature = "grammar-jsonc")]
    g.push(BundledGrammar {
        name: "jsonc",
        scope: "source.json.comments",
        aliases: &[],
        json: include_str!("../assets/grammars/jsonc.json"),
    });
    #[cfg(feature = "grammar-jsonl")]
    g.push(BundledGrammar {
        name: "jsonl",
        scope: "source.json.lines",
        aliases: &[],
        json: include_str!("../assets/grammars/jsonl.json"),
    });
    #[cfg(feature = "grammar-jsonnet")]
    g.push(BundledGrammar {
        name: "jsonnet",
        scope: "source.jsonnet",
        aliases: &[],
        json: include_str!("../assets/grammars/jsonnet.json"),
    });
    #[cfg(feature = "grammar-jssm")]
    g.push(BundledGrammar {
        name: "jssm",
        scope: "source.jssm",
        aliases: &["fsl"],
        json: include_str!("../assets/grammars/jssm.json"),
    });
    #[cfg(feature = "grammar-jsx")]
    g.push(BundledGrammar {
        name: "jsx",
        scope: "source.js.jsx",
        aliases: &[],
        json: include_str!("../assets/grammars/jsx.json"),
    });
    #[cfg(feature = "grammar-julia")]
    g.push(BundledGrammar {
        name: "julia",
        scope: "source.julia",
        aliases: &["jl"],
        json: include_str!("../assets/grammars/julia.json"),
    });
    #[cfg(feature = "grammar-just")]
    g.push(BundledGrammar {
        name: "just",
        scope: "source.just",
        aliases: &[],
        json: include_str!("../assets/grammars/just.json"),
    });
    #[cfg(feature = "grammar-kdl")]
    g.push(BundledGrammar {
        name: "kdl",
        scope: "source.kdl",
        aliases: &[],
        json: include_str!("../assets/grammars/kdl.json"),
    });
    #[cfg(feature = "grammar-kotlin")]
    g.push(BundledGrammar {
        name: "kotlin",
        scope: "source.kotlin",
        aliases: &["kt", "kts"],
        json: include_str!("../assets/grammars/kotlin.json"),
    });
    #[cfg(feature = "grammar-kusto")]
    g.push(BundledGrammar {
        name: "kusto",
        scope: "source.kusto",
        aliases: &["kql"],
        json: include_str!("../assets/grammars/kusto.json"),
    });
    #[cfg(feature = "grammar-latex")]
    g.push(BundledGrammar {
        name: "latex",
        scope: "text.tex.latex",
        aliases: &[],
        json: include_str!("../assets/grammars/latex.json"),
    });
    #[cfg(feature = "grammar-lean")]
    g.push(BundledGrammar {
        name: "lean",
        scope: "source.lean4",
        aliases: &["lean4"],
        json: include_str!("../assets/grammars/lean.json"),
    });
    #[cfg(feature = "grammar-less")]
    g.push(BundledGrammar {
        name: "less",
        scope: "source.css.less",
        aliases: &[],
        json: include_str!("../assets/grammars/less.json"),
    });
    #[cfg(feature = "grammar-liquid")]
    g.push(BundledGrammar {
        name: "liquid",
        scope: "text.html.liquid",
        aliases: &[],
        json: include_str!("../assets/grammars/liquid.json"),
    });
    #[cfg(feature = "grammar-llvm")]
    g.push(BundledGrammar {
        name: "llvm",
        scope: "source.llvm",
        aliases: &[],
        json: include_str!("../assets/grammars/llvm.json"),
    });
    #[cfg(feature = "grammar-log")]
    g.push(BundledGrammar {
        name: "log",
        scope: "text.log",
        aliases: &[],
        json: include_str!("../assets/grammars/log.json"),
    });
    #[cfg(feature = "grammar-logo")]
    g.push(BundledGrammar {
        name: "logo",
        scope: "source.logo",
        aliases: &[],
        json: include_str!("../assets/grammars/logo.json"),
    });
    #[cfg(feature = "grammar-lua")]
    g.push(BundledGrammar {
        name: "lua",
        scope: "source.lua",
        aliases: &[],
        json: include_str!("../assets/grammars/lua.json"),
    });
    #[cfg(feature = "grammar-luau")]
    g.push(BundledGrammar {
        name: "luau",
        scope: "source.luau",
        aliases: &[],
        json: include_str!("../assets/grammars/luau.json"),
    });
    #[cfg(feature = "grammar-make")]
    g.push(BundledGrammar {
        name: "make",
        scope: "source.makefile",
        aliases: &["makefile"],
        json: include_str!("../assets/grammars/make.json"),
    });
    #[cfg(feature = "grammar-markdown")]
    g.push(BundledGrammar {
        name: "markdown",
        scope: "text.html.markdown",
        aliases: &["md"],
        json: include_str!("../assets/grammars/markdown.json"),
    });
    #[cfg(feature = "grammar-markdown-nix")]
    g.push(BundledGrammar {
        name: "markdown-nix",
        scope: "markdown.nix.codeblock",
        aliases: &[],
        json: include_str!("../assets/grammars/markdown-nix.json"),
    });
    #[cfg(feature = "grammar-markdown-vue")]
    g.push(BundledGrammar {
        name: "markdown-vue",
        scope: "markdown.vue.codeblock",
        aliases: &[],
        json: include_str!("../assets/grammars/markdown-vue.json"),
    });
    #[cfg(feature = "grammar-marko")]
    g.push(BundledGrammar {
        name: "marko",
        scope: "text.marko",
        aliases: &[],
        json: include_str!("../assets/grammars/marko.json"),
    });
    #[cfg(feature = "grammar-matlab")]
    g.push(BundledGrammar {
        name: "matlab",
        scope: "source.matlab",
        aliases: &[],
        json: include_str!("../assets/grammars/matlab.json"),
    });
    #[cfg(feature = "grammar-mdc")]
    g.push(BundledGrammar {
        name: "mdc",
        scope: "text.markdown.mdc.standalone",
        aliases: &[],
        json: include_str!("../assets/grammars/mdc.json"),
    });
    #[cfg(feature = "grammar-mdx")]
    g.push(BundledGrammar {
        name: "mdx",
        scope: "source.mdx",
        aliases: &[],
        json: include_str!("../assets/grammars/mdx.json"),
    });
    #[cfg(feature = "grammar-mermaid")]
    g.push(BundledGrammar {
        name: "mermaid",
        scope: "markdown.mermaid.codeblock",
        aliases: &["mmd"],
        json: include_str!("../assets/grammars/mermaid.json"),
    });
    #[cfg(feature = "grammar-mipsasm")]
    g.push(BundledGrammar {
        name: "mipsasm",
        scope: "source.mips",
        aliases: &["mips"],
        json: include_str!("../assets/grammars/mipsasm.json"),
    });
    #[cfg(feature = "grammar-mojo")]
    g.push(BundledGrammar {
        name: "mojo",
        scope: "source.mojo",
        aliases: &[],
        json: include_str!("../assets/grammars/mojo.json"),
    });
    #[cfg(feature = "grammar-moonbit")]
    g.push(BundledGrammar {
        name: "moonbit",
        scope: "source.moonbit",
        aliases: &["mbt", "mbti"],
        json: include_str!("../assets/grammars/moonbit.json"),
    });
    #[cfg(feature = "grammar-move")]
    g.push(BundledGrammar {
        name: "move",
        scope: "source.move",
        aliases: &[],
        json: include_str!("../assets/grammars/move.json"),
    });
    #[cfg(feature = "grammar-narrat")]
    g.push(BundledGrammar {
        name: "narrat",
        scope: "source.narrat",
        aliases: &["nar"],
        json: include_str!("../assets/grammars/narrat.json"),
    });
    #[cfg(feature = "grammar-nextflow")]
    g.push(BundledGrammar {
        name: "nextflow",
        scope: "source.nextflow",
        aliases: &["nf"],
        json: include_str!("../assets/grammars/nextflow.json"),
    });
    #[cfg(feature = "grammar-nextflow-groovy")]
    g.push(BundledGrammar {
        name: "nextflow-groovy",
        scope: "source.nextflow-groovy",
        aliases: &[],
        json: include_str!("../assets/grammars/nextflow-groovy.json"),
    });
    #[cfg(feature = "grammar-nginx")]
    g.push(BundledGrammar {
        name: "nginx",
        scope: "source.nginx",
        aliases: &[],
        json: include_str!("../assets/grammars/nginx.json"),
    });
    #[cfg(feature = "grammar-nim")]
    g.push(BundledGrammar {
        name: "nim",
        scope: "source.nim",
        aliases: &[],
        json: include_str!("../assets/grammars/nim.json"),
    });
    #[cfg(feature = "grammar-nix")]
    g.push(BundledGrammar {
        name: "nix",
        scope: "source.nix",
        aliases: &[],
        json: include_str!("../assets/grammars/nix.json"),
    });
    #[cfg(feature = "grammar-nushell")]
    g.push(BundledGrammar {
        name: "nushell",
        scope: "source.nushell",
        aliases: &["nu"],
        json: include_str!("../assets/grammars/nushell.json"),
    });
    #[cfg(feature = "grammar-objective-c")]
    g.push(BundledGrammar {
        name: "objective-c",
        scope: "source.objc",
        aliases: &["objc"],
        json: include_str!("../assets/grammars/objective-c.json"),
    });
    #[cfg(feature = "grammar-objective-cpp")]
    g.push(BundledGrammar {
        name: "objective-cpp",
        scope: "source.objcpp",
        aliases: &[],
        json: include_str!("../assets/grammars/objective-cpp.json"),
    });
    #[cfg(feature = "grammar-ocaml")]
    g.push(BundledGrammar {
        name: "ocaml",
        scope: "source.ocaml",
        aliases: &[],
        json: include_str!("../assets/grammars/ocaml.json"),
    });
    #[cfg(feature = "grammar-odin")]
    g.push(BundledGrammar {
        name: "odin",
        scope: "source.odin",
        aliases: &[],
        json: include_str!("../assets/grammars/odin.json"),
    });
    #[cfg(feature = "grammar-openscad")]
    g.push(BundledGrammar {
        name: "openscad",
        scope: "source.scad",
        aliases: &["scad"],
        json: include_str!("../assets/grammars/openscad.json"),
    });
    #[cfg(feature = "grammar-org")]
    g.push(BundledGrammar {
        name: "org",
        scope: "source.org",
        aliases: &[],
        json: include_str!("../assets/grammars/org.json"),
    });
    #[cfg(feature = "grammar-pascal")]
    g.push(BundledGrammar {
        name: "pascal",
        scope: "source.pascal",
        aliases: &[],
        json: include_str!("../assets/grammars/pascal.json"),
    });
    #[cfg(feature = "grammar-perl")]
    g.push(BundledGrammar {
        name: "perl",
        scope: "source.perl",
        aliases: &[],
        json: include_str!("../assets/grammars/perl.json"),
    });
    #[cfg(feature = "grammar-php")]
    g.push(BundledGrammar {
        name: "php",
        scope: "source.php",
        aliases: &[],
        json: include_str!("../assets/grammars/php.json"),
    });
    #[cfg(feature = "grammar-pkl")]
    g.push(BundledGrammar {
        name: "pkl",
        scope: "source.pkl",
        aliases: &[],
        json: include_str!("../assets/grammars/pkl.json"),
    });
    #[cfg(feature = "grammar-plsql")]
    g.push(BundledGrammar {
        name: "plsql",
        scope: "source.plsql.oracle",
        aliases: &[],
        json: include_str!("../assets/grammars/plsql.json"),
    });
    #[cfg(feature = "grammar-po")]
    g.push(BundledGrammar {
        name: "po",
        scope: "source.po",
        aliases: &["pot", "potx"],
        json: include_str!("../assets/grammars/po.json"),
    });
    #[cfg(feature = "grammar-polar")]
    g.push(BundledGrammar {
        name: "polar",
        scope: "source.polar",
        aliases: &[],
        json: include_str!("../assets/grammars/polar.json"),
    });
    #[cfg(feature = "grammar-postcss")]
    g.push(BundledGrammar {
        name: "postcss",
        scope: "source.css.postcss",
        aliases: &[],
        json: include_str!("../assets/grammars/postcss.json"),
    });
    #[cfg(feature = "grammar-powerquery")]
    g.push(BundledGrammar {
        name: "powerquery",
        scope: "source.powerquery",
        aliases: &[],
        json: include_str!("../assets/grammars/powerquery.json"),
    });
    #[cfg(feature = "grammar-powershell")]
    g.push(BundledGrammar {
        name: "powershell",
        scope: "source.powershell",
        aliases: &["ps", "ps1"],
        json: include_str!("../assets/grammars/powershell.json"),
    });
    #[cfg(feature = "grammar-prisma")]
    g.push(BundledGrammar {
        name: "prisma",
        scope: "source.prisma",
        aliases: &[],
        json: include_str!("../assets/grammars/prisma.json"),
    });
    #[cfg(feature = "grammar-prolog")]
    g.push(BundledGrammar {
        name: "prolog",
        scope: "source.prolog",
        aliases: &[],
        json: include_str!("../assets/grammars/prolog.json"),
    });
    #[cfg(feature = "grammar-proto")]
    g.push(BundledGrammar {
        name: "proto",
        scope: "source.proto",
        aliases: &["protobuf"],
        json: include_str!("../assets/grammars/proto.json"),
    });
    #[cfg(feature = "grammar-pug")]
    g.push(BundledGrammar {
        name: "pug",
        scope: "text.pug",
        aliases: &["jade"],
        json: include_str!("../assets/grammars/pug.json"),
    });
    #[cfg(feature = "grammar-puppet")]
    g.push(BundledGrammar {
        name: "puppet",
        scope: "source.puppet",
        aliases: &[],
        json: include_str!("../assets/grammars/puppet.json"),
    });
    #[cfg(feature = "grammar-purescript")]
    g.push(BundledGrammar {
        name: "purescript",
        scope: "source.purescript",
        aliases: &[],
        json: include_str!("../assets/grammars/purescript.json"),
    });
    #[cfg(feature = "grammar-python")]
    g.push(BundledGrammar {
        name: "python",
        scope: "source.python",
        aliases: &["py"],
        json: include_str!("../assets/grammars/python.json"),
    });
    #[cfg(feature = "grammar-qml")]
    g.push(BundledGrammar {
        name: "qml",
        scope: "source.qml",
        aliases: &[],
        json: include_str!("../assets/grammars/qml.json"),
    });
    #[cfg(feature = "grammar-qmldir")]
    g.push(BundledGrammar {
        name: "qmldir",
        scope: "source.qmldir",
        aliases: &[],
        json: include_str!("../assets/grammars/qmldir.json"),
    });
    #[cfg(feature = "grammar-qss")]
    g.push(BundledGrammar {
        name: "qss",
        scope: "source.qss",
        aliases: &[],
        json: include_str!("../assets/grammars/qss.json"),
    });
    #[cfg(feature = "grammar-r")]
    g.push(BundledGrammar {
        name: "r",
        scope: "source.r",
        aliases: &[],
        json: include_str!("../assets/grammars/r.json"),
    });
    #[cfg(feature = "grammar-racket")]
    g.push(BundledGrammar {
        name: "racket",
        scope: "source.racket",
        aliases: &[],
        json: include_str!("../assets/grammars/racket.json"),
    });
    #[cfg(feature = "grammar-raku")]
    g.push(BundledGrammar {
        name: "raku",
        scope: "source.perl.6",
        aliases: &["perl6"],
        json: include_str!("../assets/grammars/raku.json"),
    });
    #[cfg(feature = "grammar-razor")]
    g.push(BundledGrammar {
        name: "razor",
        scope: "text.aspnetcorerazor",
        aliases: &[],
        json: include_str!("../assets/grammars/razor.json"),
    });
    #[cfg(feature = "grammar-reg")]
    g.push(BundledGrammar {
        name: "reg",
        scope: "source.reg",
        aliases: &[],
        json: include_str!("../assets/grammars/reg.json"),
    });
    #[cfg(feature = "grammar-regexp")]
    g.push(BundledGrammar {
        name: "regexp",
        scope: "source.regexp.python",
        aliases: &["regex"],
        json: include_str!("../assets/grammars/regexp.json"),
    });
    #[cfg(feature = "grammar-rel")]
    g.push(BundledGrammar {
        name: "rel",
        scope: "source.rel",
        aliases: &[],
        json: include_str!("../assets/grammars/rel.json"),
    });
    #[cfg(feature = "grammar-riscv")]
    g.push(BundledGrammar {
        name: "riscv",
        scope: "source.riscv",
        aliases: &[],
        json: include_str!("../assets/grammars/riscv.json"),
    });
    #[cfg(feature = "grammar-ron")]
    g.push(BundledGrammar {
        name: "ron",
        scope: "source.ron",
        aliases: &[],
        json: include_str!("../assets/grammars/ron.json"),
    });
    #[cfg(feature = "grammar-rosmsg")]
    g.push(BundledGrammar {
        name: "rosmsg",
        scope: "source.rosmsg",
        aliases: &[],
        json: include_str!("../assets/grammars/rosmsg.json"),
    });
    #[cfg(feature = "grammar-rst")]
    g.push(BundledGrammar {
        name: "rst",
        scope: "source.rst",
        aliases: &[],
        json: include_str!("../assets/grammars/rst.json"),
    });
    #[cfg(feature = "grammar-ruby")]
    g.push(BundledGrammar {
        name: "ruby",
        scope: "source.ruby",
        aliases: &["rb"],
        json: include_str!("../assets/grammars/ruby.json"),
    });
    #[cfg(feature = "grammar-rust")]
    g.push(BundledGrammar {
        name: "rust",
        scope: "source.rust",
        aliases: &["rs"],
        json: include_str!("../assets/grammars/rust.json"),
    });
    #[cfg(feature = "grammar-sas")]
    g.push(BundledGrammar {
        name: "sas",
        scope: "source.sas",
        aliases: &[],
        json: include_str!("../assets/grammars/sas.json"),
    });
    #[cfg(feature = "grammar-sass")]
    g.push(BundledGrammar {
        name: "sass",
        scope: "source.sass",
        aliases: &[],
        json: include_str!("../assets/grammars/sass.json"),
    });
    #[cfg(feature = "grammar-scala")]
    g.push(BundledGrammar {
        name: "scala",
        scope: "source.scala",
        aliases: &[],
        json: include_str!("../assets/grammars/scala.json"),
    });
    #[cfg(feature = "grammar-scheme")]
    g.push(BundledGrammar {
        name: "scheme",
        scope: "source.scheme",
        aliases: &[],
        json: include_str!("../assets/grammars/scheme.json"),
    });
    #[cfg(feature = "grammar-scss")]
    g.push(BundledGrammar {
        name: "scss",
        scope: "source.css.scss",
        aliases: &[],
        json: include_str!("../assets/grammars/scss.json"),
    });
    #[cfg(feature = "grammar-sdbl")]
    g.push(BundledGrammar {
        name: "sdbl",
        scope: "source.sdbl",
        aliases: &["1c-query"],
        json: include_str!("../assets/grammars/sdbl.json"),
    });
    #[cfg(feature = "grammar-shaderlab")]
    g.push(BundledGrammar {
        name: "shaderlab",
        scope: "source.shaderlab",
        aliases: &["shader"],
        json: include_str!("../assets/grammars/shaderlab.json"),
    });
    #[cfg(feature = "grammar-shellscript")]
    g.push(BundledGrammar {
        name: "shellscript",
        scope: "source.shell",
        aliases: &["bash", "sh", "shell", "zsh"],
        json: include_str!("../assets/grammars/shellscript.json"),
    });
    #[cfg(feature = "grammar-shellsession")]
    g.push(BundledGrammar {
        name: "shellsession",
        scope: "text.shell-session",
        aliases: &["console"],
        json: include_str!("../assets/grammars/shellsession.json"),
    });
    #[cfg(feature = "grammar-smalltalk")]
    g.push(BundledGrammar {
        name: "smalltalk",
        scope: "source.smalltalk",
        aliases: &[],
        json: include_str!("../assets/grammars/smalltalk.json"),
    });
    #[cfg(feature = "grammar-solidity")]
    g.push(BundledGrammar {
        name: "solidity",
        scope: "source.solidity",
        aliases: &[],
        json: include_str!("../assets/grammars/solidity.json"),
    });
    #[cfg(feature = "grammar-soy")]
    g.push(BundledGrammar {
        name: "soy",
        scope: "text.html.soy",
        aliases: &["closure-templates"],
        json: include_str!("../assets/grammars/soy.json"),
    });
    #[cfg(feature = "grammar-sparql")]
    g.push(BundledGrammar {
        name: "sparql",
        scope: "source.sparql",
        aliases: &[],
        json: include_str!("../assets/grammars/sparql.json"),
    });
    #[cfg(feature = "grammar-splunk")]
    g.push(BundledGrammar {
        name: "splunk",
        scope: "source.splunk_search",
        aliases: &["spl"],
        json: include_str!("../assets/grammars/splunk.json"),
    });
    #[cfg(feature = "grammar-sql")]
    g.push(BundledGrammar {
        name: "sql",
        scope: "source.sql",
        aliases: &[],
        json: include_str!("../assets/grammars/sql.json"),
    });
    #[cfg(feature = "grammar-ssh-config")]
    g.push(BundledGrammar {
        name: "ssh-config",
        scope: "source.ssh-config",
        aliases: &[],
        json: include_str!("../assets/grammars/ssh-config.json"),
    });
    #[cfg(feature = "grammar-stata")]
    g.push(BundledGrammar {
        name: "stata",
        scope: "source.stata",
        aliases: &[],
        json: include_str!("../assets/grammars/stata.json"),
    });
    #[cfg(feature = "grammar-stylus")]
    g.push(BundledGrammar {
        name: "stylus",
        scope: "source.stylus",
        aliases: &["styl"],
        json: include_str!("../assets/grammars/stylus.json"),
    });
    #[cfg(feature = "grammar-surrealql")]
    g.push(BundledGrammar {
        name: "surrealql",
        scope: "source.surrealql",
        aliases: &["surql"],
        json: include_str!("../assets/grammars/surrealql.json"),
    });
    #[cfg(feature = "grammar-svelte")]
    g.push(BundledGrammar {
        name: "svelte",
        scope: "source.svelte",
        aliases: &[],
        json: include_str!("../assets/grammars/svelte.json"),
    });
    #[cfg(feature = "grammar-swift")]
    g.push(BundledGrammar {
        name: "swift",
        scope: "source.swift",
        aliases: &[],
        json: include_str!("../assets/grammars/swift.json"),
    });
    #[cfg(feature = "grammar-system-verilog")]
    g.push(BundledGrammar {
        name: "system-verilog",
        scope: "source.systemverilog",
        aliases: &[],
        json: include_str!("../assets/grammars/system-verilog.json"),
    });
    #[cfg(feature = "grammar-systemd")]
    g.push(BundledGrammar {
        name: "systemd",
        scope: "source.systemd",
        aliases: &[],
        json: include_str!("../assets/grammars/systemd.json"),
    });
    #[cfg(feature = "grammar-talonscript")]
    g.push(BundledGrammar {
        name: "talonscript",
        scope: "source.talon",
        aliases: &["talon"],
        json: include_str!("../assets/grammars/talonscript.json"),
    });
    #[cfg(feature = "grammar-tasl")]
    g.push(BundledGrammar {
        name: "tasl",
        scope: "source.tasl",
        aliases: &[],
        json: include_str!("../assets/grammars/tasl.json"),
    });
    #[cfg(feature = "grammar-tcl")]
    g.push(BundledGrammar {
        name: "tcl",
        scope: "source.tcl",
        aliases: &[],
        json: include_str!("../assets/grammars/tcl.json"),
    });
    #[cfg(feature = "grammar-templ")]
    g.push(BundledGrammar {
        name: "templ",
        scope: "source.templ",
        aliases: &[],
        json: include_str!("../assets/grammars/templ.json"),
    });
    #[cfg(feature = "grammar-terraform")]
    g.push(BundledGrammar {
        name: "terraform",
        scope: "source.hcl.terraform",
        aliases: &["tf", "tfvars"],
        json: include_str!("../assets/grammars/terraform.json"),
    });
    #[cfg(feature = "grammar-tex")]
    g.push(BundledGrammar {
        name: "tex",
        scope: "text.tex",
        aliases: &[],
        json: include_str!("../assets/grammars/tex.json"),
    });
    #[cfg(feature = "grammar-toml")]
    g.push(BundledGrammar {
        name: "toml",
        scope: "source.toml",
        aliases: &[],
        json: include_str!("../assets/grammars/toml.json"),
    });
    #[cfg(feature = "grammar-ts-tags")]
    g.push(BundledGrammar {
        name: "ts-tags",
        scope: "source.ts.tags",
        aliases: &["lit"],
        json: include_str!("../assets/grammars/ts-tags.json"),
    });
    #[cfg(feature = "grammar-tsv")]
    g.push(BundledGrammar {
        name: "tsv",
        scope: "text.tsv",
        aliases: &[],
        json: include_str!("../assets/grammars/tsv.json"),
    });
    #[cfg(feature = "grammar-tsx")]
    g.push(BundledGrammar {
        name: "tsx",
        scope: "source.tsx",
        aliases: &[],
        json: include_str!("../assets/grammars/tsx.json"),
    });
    #[cfg(feature = "grammar-turtle")]
    g.push(BundledGrammar {
        name: "turtle",
        scope: "source.turtle",
        aliases: &[],
        json: include_str!("../assets/grammars/turtle.json"),
    });
    #[cfg(feature = "grammar-twig")]
    g.push(BundledGrammar {
        name: "twig",
        scope: "text.html.twig",
        aliases: &[],
        json: include_str!("../assets/grammars/twig.json"),
    });
    #[cfg(feature = "grammar-typescript")]
    g.push(BundledGrammar {
        name: "typescript",
        scope: "source.ts",
        aliases: &["ts", "cts", "mts"],
        json: include_str!("../assets/grammars/typescript.json"),
    });
    #[cfg(feature = "grammar-typespec")]
    g.push(BundledGrammar {
        name: "typespec",
        scope: "source.tsp",
        aliases: &["tsp"],
        json: include_str!("../assets/grammars/typespec.json"),
    });
    #[cfg(feature = "grammar-typst")]
    g.push(BundledGrammar {
        name: "typst",
        scope: "source.typst",
        aliases: &["typ"],
        json: include_str!("../assets/grammars/typst.json"),
    });
    #[cfg(feature = "grammar-v")]
    g.push(BundledGrammar {
        name: "v",
        scope: "source.v",
        aliases: &[],
        json: include_str!("../assets/grammars/v.json"),
    });
    #[cfg(feature = "grammar-vala")]
    g.push(BundledGrammar {
        name: "vala",
        scope: "source.vala",
        aliases: &[],
        json: include_str!("../assets/grammars/vala.json"),
    });
    #[cfg(feature = "grammar-vb")]
    g.push(BundledGrammar {
        name: "vb",
        scope: "source.asp.vb.net",
        aliases: &["cmd"],
        json: include_str!("../assets/grammars/vb.json"),
    });
    #[cfg(feature = "grammar-verilog")]
    g.push(BundledGrammar {
        name: "verilog",
        scope: "source.verilog",
        aliases: &[],
        json: include_str!("../assets/grammars/verilog.json"),
    });
    #[cfg(feature = "grammar-vhdl")]
    g.push(BundledGrammar {
        name: "vhdl",
        scope: "source.vhdl",
        aliases: &[],
        json: include_str!("../assets/grammars/vhdl.json"),
    });
    #[cfg(feature = "grammar-viml")]
    g.push(BundledGrammar {
        name: "viml",
        scope: "source.viml",
        aliases: &["vim", "vimscript"],
        json: include_str!("../assets/grammars/viml.json"),
    });
    #[cfg(feature = "grammar-vue")]
    g.push(BundledGrammar {
        name: "vue",
        scope: "text.html.vue",
        aliases: &[],
        json: include_str!("../assets/grammars/vue.json"),
    });
    #[cfg(feature = "grammar-vue-directives")]
    g.push(BundledGrammar {
        name: "vue-directives",
        scope: "vue.directives",
        aliases: &[],
        json: include_str!("../assets/grammars/vue-directives.json"),
    });
    #[cfg(feature = "grammar-vue-html")]
    g.push(BundledGrammar {
        name: "vue-html",
        scope: "text.html.vue-html",
        aliases: &[],
        json: include_str!("../assets/grammars/vue-html.json"),
    });
    #[cfg(feature = "grammar-vue-interpolations")]
    g.push(BundledGrammar {
        name: "vue-interpolations",
        scope: "vue.interpolations",
        aliases: &[],
        json: include_str!("../assets/grammars/vue-interpolations.json"),
    });
    #[cfg(feature = "grammar-vue-sfc-style-variable-injection")]
    g.push(BundledGrammar {
        name: "vue-sfc-style-variable-injection",
        scope: "vue.sfc.style.variable.injection",
        aliases: &[],
        json: include_str!("../assets/grammars/vue-sfc-style-variable-injection.json"),
    });
    #[cfg(feature = "grammar-vue-vine")]
    g.push(BundledGrammar {
        name: "vue-vine",
        scope: "source.vue-vine",
        aliases: &[],
        json: include_str!("../assets/grammars/vue-vine.json"),
    });
    #[cfg(feature = "grammar-vyper")]
    g.push(BundledGrammar {
        name: "vyper",
        scope: "source.vyper",
        aliases: &["vy"],
        json: include_str!("../assets/grammars/vyper.json"),
    });
    #[cfg(feature = "grammar-wasm")]
    g.push(BundledGrammar {
        name: "wasm",
        scope: "source.wat",
        aliases: &[],
        json: include_str!("../assets/grammars/wasm.json"),
    });
    #[cfg(feature = "grammar-wenyan")]
    g.push(BundledGrammar {
        name: "wenyan",
        scope: "source.wenyan",
        aliases: &["文言"],
        json: include_str!("../assets/grammars/wenyan.json"),
    });
    #[cfg(feature = "grammar-wgsl")]
    g.push(BundledGrammar {
        name: "wgsl",
        scope: "source.wgsl",
        aliases: &[],
        json: include_str!("../assets/grammars/wgsl.json"),
    });
    #[cfg(feature = "grammar-wikitext")]
    g.push(BundledGrammar {
        name: "wikitext",
        scope: "source.wikitext",
        aliases: &["mediawiki", "wiki"],
        json: include_str!("../assets/grammars/wikitext.json"),
    });
    #[cfg(feature = "grammar-wit")]
    g.push(BundledGrammar {
        name: "wit",
        scope: "source.wit",
        aliases: &[],
        json: include_str!("../assets/grammars/wit.json"),
    });
    #[cfg(feature = "grammar-wolfram")]
    g.push(BundledGrammar {
        name: "wolfram",
        scope: "source.wolfram",
        aliases: &["wl"],
        json: include_str!("../assets/grammars/wolfram.json"),
    });
    #[cfg(feature = "grammar-xml")]
    g.push(BundledGrammar {
        name: "xml",
        scope: "text.xml",
        aliases: &[],
        json: include_str!("../assets/grammars/xml.json"),
    });
    #[cfg(feature = "grammar-xsl")]
    g.push(BundledGrammar {
        name: "xsl",
        scope: "text.xml.xsl",
        aliases: &[],
        json: include_str!("../assets/grammars/xsl.json"),
    });
    #[cfg(feature = "grammar-yaml")]
    g.push(BundledGrammar {
        name: "yaml",
        scope: "source.yaml",
        aliases: &["yml"],
        json: include_str!("../assets/grammars/yaml.json"),
    });
    #[cfg(feature = "grammar-zenscript")]
    g.push(BundledGrammar {
        name: "zenscript",
        scope: "source.zenscript",
        aliases: &[],
        json: include_str!("../assets/grammars/zenscript.json"),
    });
    #[cfg(feature = "grammar-zig")]
    g.push(BundledGrammar {
        name: "zig",
        scope: "source.zig",
        aliases: &[],
        json: include_str!("../assets/grammars/zig.json"),
    });
    g
}
